### PR TITLE
replace pyav with av

### PR DESCRIPTION
**Pull request by dotlambda**

### CODE REVIEW

**Comment by dotlambda** [comment]
Why was this closed? Upstream recommends using av rather than pyav: https://pypi.org/project/pyav/

> Notice: [PyAV](https://github.com/PyAV-Org/PyAV) (upstream) and pyav have been merged! There is no reason to use pyav unless you want LGPLv3 builds!

**Comment by WyattBlue** [comment]
Do you know who wrote that?

**Comment by dotlambda** [comment]
I assume you did.
Anyway, it's not nice to have both pyav and av installed on my system. That's why I suggested this change.

**Comment by dotlambda** [comment]
> This PR wouldn't fix that since auto-editor could require a different version of PyAV than whatever other tool you're using.

It just as well might not. But as is, it will always.

**Pull request closed without merging**
